export default {
    MARK_NOTIFICATION_AS_READ_BY_ID: 'MARK_NOTIFICATION_AS_READ_BY_ID',
    MARK_ALL_NOTIFICATION_AS_READ: 'MARK_ALL_NOTIFICATION_AS_READ',
    START_NOTIFICAION_FETCH: 'START_NOTIFICAION_FETCH',
    FINISH_NOTIFICAION_FETCH: 'FINISH_NOTIFICAION_FETCH',
    RECEIVE_NOTIFICATIONS: 'RECEIVE_NOTIFICATIONS',
    START_LOGIN:'START_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    CHANGE_AVATAR: 'CHANGE_AVATAR'

}